version: '3.3'

services:
  logger:
    image: ghcr.io/cdwiegand/udp_log_receiver
    build:
      context: .
    restart: always
    ports:
      - "10000:10000/udp"
      - "8080:8080"
    environment:
      - USE_CONSOLE=false
